Update introduction.md
project-trident/trident-website pull request #28
Opened 2019-02-14 02:29 UTC by Mrt134

Add "Security" subsection

2019-02-15 02:17 UTC, q5sys commented on hugo-site/content/docs/introduction.md
> +-   **Naturally immune to viruses and other malware:** Most viruses are written to exploit the Windows operating system.
-   **Naturally immune to viruses and other malware written for other Operating Systems:** Most viruses are written to exploit the Windows operating system.

2019-02-15 02:18 UTC, q5sys commented on hugo-site/content/docs/introduction.md
> +    Files and directories can only be modified by root any any users and groups with permission.
"any any" needs to be fixed

2019-02-15 02:19 UTC, q5sys commented on hugo-site/content/docs/introduction.md
> +    The firewall does not allow any inbound connections to the computer.
"...connections to the computer unless the user authorizes them."

2019-02-15 02:19 UTC, q5sys commented on hugo-site/content/docs/introduction.md
> +-   **SSH is disabled:** SSH can only be enabled by the administrator (root).
"SSH is disabled by default:"

2019-02-15 02:19 UTC, q5sys commented on hugo-site/content/docs/introduction.md
> +    This prevents bots and outside individuals from accessing the Project Trident system.
"...from accessing a Project Trident system."

2019-02-15 02:20 UTC, q5sys reviewed
Just a few changes to be more specific, and a few grammatical fixes.

2019-02-15 02:22 UTC, q5sys commented on hugo-site/content/docs/introduction.md
> +The Wikipedia entry on ZFS provides an excellent starting point to learn about its features.
Should we add the wikipedia link here since we reference it?

2019-02-19 14:48 UTC, beanpole135 requested changes
Found a few simple errors. Once those are fixed I think this is ready to be merged.

2019-02-19 14:48 UTC, beanpole135 commented on hugo-site/content/docs/introduction.md
> +  If SSH access is required, add `sshd\_enable=YES` to **/etc/rc.conf**.
This line needs to be deleted. The sshd_enable=YES lines are not needed with OpenRC

2019-02-19 14:48 UTC, beanpole135 commented on hugo-site/content/docs/introduction.md
> +  If SSH access is required, add `sshd\_enable=YES` to **/etc/rc.conf**.
Perhaps add a line detailing the `rc-update add sshd` command to use to enable it at bootup.

2019-02-19 14:48 UTC, beanpole135 commented on hugo-site/content/docs/introduction.md
> +  The first user created during installation is added to the *wheel* group.
Both *wheel* and/or *operator* groups need to be mentioned here.

2019-02-19 14:48 UTC, beanpole135 commented on hugo-site/content/docs/introduction.md
> +  Use the User Configuration in Desktop Settings to add other users to the *wheel* group.
Same thing here: *wheel* and/or *operator* groups.

2019-02-19 14:48 UTC, beanpole135 commented on hugo-site/content/docs/introduction.md
> +- **sudo is installed:** `sudo` allows users in the *wheel* group permission to run an administrative command after typing the user password, not the *root* password.
*wheel* and/or *operator* groups are used by sudo

2019-02-20 21:06 UTC, beanpole135 approved these changes
LGTM

2019-02-20 21:27 UTC, merged