Add converted VirtualBox VM create article.
project-trident/trident-website pull request #32
Opened 2019-02-22 22:00 UTC by Mrt134

Includes images in a new directory.

2019-03-04 13:01 UTC, beanpole135 requested changes

2019-03-04 13:01 UTC, beanpole135 commented on hugo-site/content/docs/virtualbox-create-vm.md
> +Running VirtualBox on a Project Trident system for the first time automatically gives the user account that started VirtualBox the necessary permissions to run the application.
Not quite: Any user that wants to use VirtualBox on a PT host needs to add themselves to the "vboxusers" group and then logout/login - otherwise the VBox file permissions get all screwy.

2019-03-04 13:01 UTC, beanpole135 commented on hugo-site/content/docs/virtualbox-create-vm.md
> +
Might be a good idea to put a quick note/table at the top with the key points for running PT as a guest VM:
OS Type: BSD / FreeBSD (64-bit)
Memory: 2048MB (minimum), 4096MB (recommended)
Disk Space: 15GB (minimum), 20GB (recommended)
CPUs: 1+

2019-03-19 02:30 UTC, Mrt134 commented
Change requests resolved.

2019-03-19 12:17 UTC, beanpole135 approved these changes
Looks good to me!

2019-03-19 12:17 UTC, merged